hounddog:
  allow_failure: true
  image:
    name: hounddogai/scanner:$HOUNDDOG_DOCKER_IMAGE_TAG
    pull_policy: always
  script:
    - python scripts/clear_gitlab_security_issues.py
    - hounddog scan 
      --output-format=gitlab 
      --output-filename=hounddog.json
      --debug
    - cat hounddog.json
  artifacts:
    reports:
      sast: hounddog.json
