hounddog:
  allow_failure: true
  image:
    name: docker:latest
  variables:
    HOUNDDOG_API_KEY: $HOUNDDOG_API_KEY
  script:
    - docker run 
      -v .:/scanpath hounddogai/scanner
      -e HOUNDDOG_API_KEY=$HOUNDDOG_API_KEY
      hounddog scan 
      --output-format=gitlab 
      --output-filename=hounddog.json
      --no-upload-scan-results
  artifacts:
    reports:
      sast: hounddog.json
#
#hounddog-weekly:
#  allow_failure: true
#  image:
#    name: hounddogai/scanner
#    pull_policy: always
#  variables:
#    HOUNDDOG_API_KEY: $HOUNDDOG_API_KEY
#    OPENAI_API_KEY: $OPENAI_API_KEY
#  script:
#    - hounddog scan --discover-data-elements
