hounddog:
  allow_failure: true
  image:
    name: hounddogai/scanner:staging
    pull_policy: always
  variables:
    HOUNDDOG_API_KEY: $HOUNDDOG_API_KEY
  script:
#    - python scripts/clear_gitlab_security_issues.py
    - hounddog scan 
      --output-format=gitlab 
      --output-filename=hounddog.json
      --debug
    - cat hounddog.json
  artifacts:
    reports:
      sast: hounddog.json
