trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: staging

steps:
  - checkout: self
    displayName: Checkout repository

  - script: pwd
    displayName: Print working directory

  - script: ls -la
    displayName: List all files in the repository

  - script: >
      docker run -t -v .:/data --pull=always
      -e AZURE_PIPELINES=1
      -e HOUNDDOG_API_KEY=$(HoundDogApiKey) 
      hounddogai/hounddog:staging hounddog scan
      --output-format=json
      --output-filename=hounddog.json
      --debug
    displayName: Run HoundDog.ai Scan

  - script: ls -la
    displayName: List all files in the repository
