trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: staging

steps:
  - checkout: self
    displayName: Checkout repository

  - script: >
      docker run --rm -t -v .:/data --pull=always
      -e AZURE_PIPELINES=1
      -e HOUNDDOG_API_KEY=$(HoundDogApiKey) 
      hounddogai/hounddog:staging hounddog scan --output-format=json > hounddog.json 2>&1 || { cat hounddog.json; exit 1; }
    displayName: Run HoundDog.ai Scan

  - script: cat hounddog.json
    displayName: Display HoundDog.ai scan results JSON
