trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: staging

steps:
  - checkout: self
    displayName: Checkout repository

  - script: >
      docker run --rm -t -v .:/data --pull=always -e AZURE_PIPELINES=1
      hounddogai/hounddog:staging hounddog definitions
    displayName: Display HoundDog.ai Definitions (Console Output)

  - script: >
      docker run --rm -t -v .:/data --pull=always -e AZURE_PIPELINES=1
      hounddogai/hounddog:staging hounddog definitions --output-format=json
    displayName: Display HoundDog.ai Definitions (JSON Output)

  - script: >
      docker run --rm -t -v .:/data --pull=always -e AZURE_PIPELINES=1 -e HOUNDDOG_API_KEY=$(HoundDogApiKey) 
      hounddogai/hounddog:staging hounddog scan
    displayName: Run HoundDog.ai Scan (Console Output)

  - script: >
      docker run --rm -t -v .:/data --pull=always -e AZURE_PIPELINES=1 -e HOUNDDOG_API_KEY=$(HoundDogApiKey) 
      hounddogai/hounddog:staging hounddog scan --output-format=json
    displayName: Run HoundDog.ai Scan (JSON Output)
