trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: staging

steps:
- checkout: self
  displayName: Checkout repository

- script: >
    docker run -t -v .:/scanpath
    -e HOUNDDOG_API_KEY=$(HoundDogApiKey) 
    hounddogai/scanner:staging hounddog scan
    --output-format=json
    --output-filename=results.json
    --debug
  displayName: Run HoundDog.ai scan

- script: cat results.json
  displayName: Display HoundDog.ai scan results JSON
