pipelines:
  branches:
    main:
      - step:
          name: Run HoundDog.ai Scan
          image: hounddogai/hounddog:staging
          script:
            - pwd
            - ls -la
            - export HOUNDDOG_API_KEY=$HOUNDDOG_API_KEY
            - hounddog scan $(pwd)
              --output-format=json 
              --output-filename=hounddog.json 
              --debug
            - ls -la
            - cat hounddog.json
