version: 2.1
jobs:
  build:
    docker:
      - image: hounddogai/scanner:staging
    steps:
      - checkout
      - run:
          name: Cat environment variable for testing
          environment:
            HOUNDDOG_API_KEY: $HOUNDDOG_API_KEY
          command: echo $HOUNDDOG_API_KEY
      - run:
          name: Run HoundDog.ai Scan
          environment:
            HOUNDDOG_API_KEY: $HOUNDDOG_API_KEY
          command: > 
            hounddog scan 
            --output-format=json 
            --output-filename=hounddog.json 
            --debug
      - run:
          name: Display HoundDog.ai scan results JSON
          command: cat hounddog.json
