version: 2.1
jobs:
  build:
    docker:
      - image: hounddogai/hounddog:staging
    steps:
      - checkout
      - run:
          name: Display HoundDog.ai Info
          command: hounddog info
      - run:
          name: Display HoundDog.ai Definitions (Console Output)
          command: hounddog definitions
      - run:
          name: Display HoundDog.ai Definitions (JSON Output)
          command: hounddog definitions --output-format=json
      - run:
          name: Run HoundDog.ai Scan (Console Output)
          command: hounddog scan
      - run:
          name: Run HoundDog.ai Scan (JSON Output)
          command: hounddog scan --output-format=json
