version: 2.1
jobs:
  build:
    docker:
      - image: hounddogai/scanner:staging
    steps:
      - checkout
      - run:
          name: Test environment variable
          command: python scripts/echo_hounddog_key.py
      - run:
          name: Run HoundDog.ai Scan
          command: > 
            hounddog scan 
            --output-format=json 
            --output-filename=hounddog.json 
            --debug
      - run:
          name: Display HoundDog.ai scan results JSON
          command: cat hounddog.json
