version: 2.1
jobs:
  build:
    docker:
      - image: hounddogai/hounddog:staging
    steps:
      - checkout
      - run:
          name: Run HoundDog.ai Scan
          command: hounddog scan --output-format=json > hounddog.json 2>&1 || { cat hounddog.json; exit 1; }
      - run:
          name: List all files in the repository
          command: ls -la
      - run:
          name: Display HoundDog.ai scan results JSON
          command: cat hounddog.json
