version: 2.1
jobs:
  build:
    docker:
      - image: hounddogai/scanner:staging
    steps:
      - checkout
      - run:
          name: Run HoundDog.ai Scan
          command: hounddog scan --output-format=console
