name: HoundDog.ai Scan Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

jobs:
  hounddog:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run HoundDog.ai Scan
        env:
          HOUNDDOG_API_KEY: ${{ secrets.HOUNDDOG_API_KEY }}
        run: hounddog scan --fail-severity-threshold=low
