name: Run HoundDog.ai Scan
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Debug this workflow via SSH
        default: false

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: hounddogai/scanner:staging
      env:
        HOUNDDOG_API_KEY: ${{ secrets.HOUNDDOG_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      volumes:
      - .:/scanpath
    # Skip pull requests created by dependabot
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Debug workflow via SSH
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Install requirements
        run: pip install httpx

      - name: Run HoundDog.ai Scan
        run: hounddog scan --output-filename=results.sarif --output-format=sarif

      - name: Print SARIF results
        run: cat results.sarif

      - name: Clear code scanning alerts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/clear_github_scan_results.py

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
